### ISSUE TITLE
"Getting Answer" from Sonoff-devices

### ISSUE THREAD

**Issue by JoeWiseman** [jp112sdl/SonoffHMLOX#45]
Hi
up to now I'm using the sonoff-devices along with the tasmota-firmware ... Connecting them to the homatic-system is done in the same way you are doing it - by an http-command.

Is there any possibility that your firmware would talk backward to the CCU by an http-command? 
Why, here is the scenario:
on the CCU there is are programms called PlugStatusON, PlugStatusOFF. When the status of the Sonoff-device is changing it calls the corresponing program via http-command (of course CCU is running the XML-API) and the CCU gets an feedback from the device.
That would be a great feature to have and would make the Sonoff-prducts real homatic member.

Of course it is possible to use a program which is getting the device-status via http-command, but this has to be done periodically without knowing if there is any real change ....

Regards
Joe

**Comment by jp112sdl** [comment]
It's implemented by default.

If you configure your CUxD channel as described in the [Wiki](https://github.com/jp112sdl/SonoffHMLOX/wiki/Homematic), you have a callback.

1.) If someone toggles the state on the device (pressing the momentary switch), the state will be set to the CUxD channel.

2.) If you change the state of your sonoff device by [http command](https://github.com/jp112sdl/SonoffHMLOX/wiki/Direkte_HTTP_Steuerung) the state will be set to the CUxD channel (if you append the option `?ts=1` 

The channel always represents the current state of the sonoff device.

XML-API is not needed.

**Comment by JoeWiseman** [comment]
Thanks a lot for answering so fast ... 
... and for bringing such good news. I have bought some S20-devices. If they will arrive, I will test it!

In the tasmota software there is a blink-feature which allows you to set up an on-time like a light in the stairway. Is something like that also possible? Or do I have to implement this by using the CCU?

In the end I like to ask if the following devices are supported:
- Sonoff Basic
- Sonoff Dual (R2)

Regards
Joe

**Comment by jp112sdl** [comment]
The SonoffHMLOX has only a few features. The idea of writing this firmware came up because I needed an active callback or bidirectional communication between the sonoff and the ccu.

The only features are on/off and a timer. 

Supported devices are (as mentioned in the README):
- Sonoff Switch (Basic)
- S20 
- SV
- Touch (1Gang)
- POW

For the Dual and Dual R2 as a dual switch, please refer to this repository: [SonoffDualHVIOHMLOX](https://github.com/jp112sdl/SonoffDualHVIOHMLOX)

For the Dual and Dual R2 as an shutter actor, please refer to this repository: [SonoffDualShutterHMLOX](https://github.com/jp112sdl/SonoffDualShutterHMLOX)

**Comment by JoeWiseman** [comment]
THANKS!!!! 
I'll try your work, as soon as my devices will arrive!
Regards
Joe
